#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_haihero="0.0.1"
  jq -n --arg haihero "$ver_haihero" '{haihero: $haihero}'
}

version "$@"
